service: rs-shop-back-lozita

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: "20201221"

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
