service: rs-shop-back-lozita

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: "20201221"
  environment:
    POSTGRES_HOST=
    POSTGRES_USER=
    POSTGRES_PASSWORD=
    POSTGRES_PORT=
    POSTGRES_DB=

functions:
  main:
    handler: dist/src/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
