export const MAX_INTEGER = 2147483647;

export const ERRORS = {
  NOT_A_POSITIVE: 'NOT_A_POSITIVE',
  NOT_A_STRING: 'NOT_A_STRING',
  NOT_INT_32: 'NOT_INT_32',
  INVALID_UUID: 'INVALID_UUID',
  NOT_AN_INTEGER: 'NOT_AN_INTEGER',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_SKIP_VALUE: 'INVALID_SKIP_VALUE',
  INVALID_LIMIT_VALUE: 'INVALID_LIMIT_VALUE',
  NOT_A_CSV: 'NOT_A_CSV',
  CANNOT_PROCESS_REQUEST: 'CANNOT_PROCESS_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  PENDING_ERROR: 'PENDING_ERROR',
};
