export const MAX_INTEGER = 2147483647;

export const ERRORS = {
  NOT_A_POSITIVE: 'NOT_A_POSITIVE',
  NOT_A_STRING: 'NOT_A_STRING',
  NOT_INT_32: 'NOT_INT_32',
  NOT_AN_INTEGER: 'NOT_AN_INTEGER',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_SKIP_VALUE: 'INVALID_SKIP_VALUE',
  INVALID_LIMIT_VALUE: 'INVALID_LIMIT_VALUE',
};
