service: rs-shop-back-lozita-products

plugins:
  - serverless-offline
  - serverless-plugin-optimize

# todo pass env
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: "20201221"
  environment:
    POSTGRES_HOST: POSTGRES_HOST
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: POSTGRES_HOST
    POSTGRES_PORT: 5632
    POSTGRES_DB: shop

functions:
  products:
    handler: dist/apps/products/src/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

