version: '3.4'
x-env-file: &env_file
  env_file:
    - ../../.env.local

services:
  db:
    image: mdillon/postgis:11
    << : *env_file
    environment:
      - TZ=Europe/Minsk
      - PGTZ=Europe/Minsk
    volumes:
      - ./_data:/var/lib/postgresql/data/
    ports:
      - "27190:5432"
    restart: always
